apiVersion: apps/v1
kind: Deployment
metadata:
  name: oxygencs
  labels:
    app: oxygencs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: oxygencs-app
  template:
    metadata:
      labels:
        app: oxygencs-app
    spec:
      containers:
      - name: oxygencs
        image: santiagochiappe/log680_oxygencs
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "250m"
            memory: "250Mi"
        envFrom:
        - configMapRef:
            name: config-oxygencs
        - secretRef:
            name: secrets-oxygencs