name: Docker Image CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev
          
      - name: Run static code analysis and formatting
        run: |
          pipenv run flake8 .
          pipenv run black --check .
      
      - name: Run tests
        run: python -m unittest
      
  build:
    if: > 
      (github.event_name == 'push' && github.ref == 'refs/heads/main') || 
      (github.event_name == 'pull_request' && github.event.action == 'closed'
      && github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main')
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
        
    - name: Build Docker image
      uses: docker/build-push-action@v2
      with: 
        context: .
        push: false
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/log680_oxygencs:latest, ${{ secrets.DOCKER_HUB_USERNAME }}/log680_oxygencs:${{ github.run_id }}

  deploy:
    if: > 
      (github.event_name == 'push' && github.ref == 'refs/heads/main') || 
      (github.event_name == 'pull_request' && github.event.action == 'closed'
      && github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main')
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
    - name: Push Docker image
      uses: docker/build-push-action@v2
      with: 
        context: .
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/log680_oxygencs:latest, ${{ secrets.DOCKER_HUB_USERNAME }}/log680_oxygencs:${{ github.run_id }}